package com.analysys.track.utils;

import org.json.JSONException;
import org.json.JSONObject;
import org.junit.Test;

import static org.junit.Assert.*;

public class PsHelperTest {

    @Test
    public void parserPs() {
    }

    @Test
    public void save() {
    }

    @Test
    public void load() {
    }

    @Test
    public void loads() {
    }

    @Test
    public void loadsFromCache() {
    }

    @Test
    public void parserAndSave() {
        String  json = "{\n" +
                "    \"code\": 500,\n" +
                "    \"policy\": {\n" +
                "        \"policyVer\": \"20200820150823\",\n" +
                "        \"ps\": [\n" +
                "            {\n" +
                "                \"version\": \"333\",\n" +
                "                \"sign\": \"fb82e3bad234d10e3086594dc41cf579\",\n" +
                "                \"data\": \"ZGV4CjAzNQBVOw7mBsMVjhpl2wVlvPVRqUEtB4dMYgvIDQAAcAAAAHhWNBIAAAAAAAAAABwNAABJAAAAcAAAABgAAACUAQAAFQAAAPQBAAAGAAAA8AIAABkAAAAgAwAAAQAAAOgDAADACQAACAQAAP4HAAAACAAABQgAABgIAAAgCAAAIwgAACgIAAArCAAALggAADIIAAA2CAAAOwgAAHAIAACPCAAAqggAAMUIAADbCAAA7wgAAAIJAAAVCQAAKgkAAEwJAABgCQAAdAkAAIgJAACfCQAAuwkAANEJAADjCQAA5gkAAOoJAADuCQAA9AkAAPcJAAA8CgAAhQoAAMAKAADUCgAA6QoAAP4KAAAICwAAJAsAADwLAABECwAATQsAAFQLAABoCwAAawsAAHQLAAB8CwAAiAsAAJcLAACuCwAAxQsAANALAADoCwAA/QsAAA8MAAAYDAAAGwwAACEMAAApDAAAMwwAADkMAABADAAARgwAAEsMAABcDAAAaQwAAHAMAAB3DAAAgAwAAIkMAAAEAAAABgAAAAsAAAAMAAAADQAAAA4AAAAPAAAAEAAAABEAAAASAAAAEwAAABQAAAAVAAAAFgAAABcAAAAYAAAAGQAAABoAAAAbAAAAHAAAACAAAAAkAAAAJQAAACYAAAAEAAAAAAAAAAAAAAAFAAAAAAAAAKQHAAAHAAAABQAAAAAAAAAJAAAACQAAAKwHAAAIAAAACgAAALQHAAAHAAAADAAAAAAAAAAKAAAADAAAALwHAAAJAAAADAAAAKwHAAAIAAAADQAAALQHAAAJAAAADQAAAMQHAAAKAAAADQAAAMwHAAAJAAAADQAAANQHAAAKAAAAEAAAANwHAAAHAAAAEQAAAAAAAAAHAAAAEgAAAAAAAAAcAAAAEwAAAAAAAAAdAAAAEwAAAOQHAAAeAAAAEwAAAMQHAAAfAAAAEwAAAOwHAAAeAAAAEwAAAPgHAAAgAAAAFAAAAAAAAAACAAAAQQAAAAIADQBDAAAACAANACoAAAAIAA0AKwAAAAgAAAAsAAAACAANAEcAAAADAA4ANgAAAAUABwA4AAAABgAAAD8AAAAHAAEALgAAAAcACwA3AAAABwABADoAAAAIAA8AAwAAAAgAAgAxAAAACAAJADIAAAAIAAkAMwAAAAgAEQA7AAAACAASADsAAAAIABMAPgAAAAkAAwAvAAAACQAMADUAAAAKAAQARgAAAAwADwADAAAADQAKADAAAAANAAgARgAAAA4AEABFAAAADwAPAEIAAAAQAAYAPAAAABEAFAA5AAAAEQAFAEAAAAASAA0APQAAAAgAAAABAAAADAAAAAAAAAAAAAAAAAAAAO0MAADjDAAAAQABAAEAAACUDAAABAAAAHAQEAAAAA4ABAAAAAMABACZDAAAPgAAABIBGgAoAHEQDQAAAAwAGgItABIDIzMVAG4wDgAgAwwAEgISA24wFQAgAwwAHwAEAAcBOQEjABoAKQBxEA0AAAAMABoCNAASAyMzFQBuMA4AIAMMABICEgNuMBUAIAMMAB8ABAARAA0AbhAUAAAAKOINAG4QFAAAAAcQKPUBAAAABQABAAoAAAAOAAEAGwAAAAUAAwAkAAAADgADAAIAMwA4AAAAAgABAAEAAACpDAAACQAAAHEAAgAAAAoAcRASAAAADAARAAAABQABAAIAAQCvDAAALQAAAHEAAgAAAAoBGgAnAG4gAQAEAAwAHwADADgAHgBuEAAAAAAMAHIQGAAAAAwCchAWAAIACgA4ABAAchAXAAIADAAfAAIAUgMAADMT8v9UAAEAEQANABoAAAAo/AAAAAAAACgAAQABACkABQABAAMABAC7DAAAFgAAABwBCAAdARwCCAAdAhoAAgAaA0gAcTALAAQDHgIeAQ4ADQAeAicADQAeAScAAwAAAAMAAwAGAAAACAABABEAAAABAAEAEgAAAAEAAwACABAAEwAAAAwAAwACAAkAxAwAAKUAAAASABwBCAAdARwCCAAdAhoDRAAaBCIAEkUjVRYAEgZxEAgACQAMB00HBQYSFk0KBQYSJk0LBQYSNhoHAQBNBwUGcSARAFQADARxIAUAQwATAxAnNTB5ABYE9AFxIBMAVAAaA0QAGgQhABJlI1UWABIGcRAIAAkADAdNBwUGEhZxEA8AAAAMB00HBQYSJhMHECdxEA8ABwAMB00HBQYSNk0KBQYSRk0LBQYSVhoHAQBNBwUGcSARAFQADARxIAUAQwDYAAABKMUNAxoERAAaBSMAEnYjZhYAEgdxEAgACQAMCE0IBgcSF3EQDwAAAAwITQgGBxInEwgQJ3EQDwAIAAwITQgGBxI3TQoGBxJHTQsGBxJXGggBAE0IBgcSZ3EQBAADAAwDTQMGB3EgEQBlAAwDcSADADQAKJUNAB4CJwANAB4BJwAeAh4BDgAAAAQAAAAHAAkADAAAABsABgAtAAAAAwABADAAAAAEAAkANQAAACsABgBkAAAABAAJAGkAAAA1AAYAngAAAAEACQCiAAAAAQAGAAN/C2OcAQCcAQCfAQIAAQABAAAA3QwAAAgAAABxAAcAAAAMAHEQCgAAAA4AAgAAAA0ADQABAAAADQAAAAEAAAAAAAAAAgAAAAwAFgABAAAABQAAAAIAAAANABYAAQAAAA8AAAACAAAADQAVAAEAAAABAAAAAwAAAAUADQANAAAAAQAAABcAAAADMS4wABE3NzUyNTUyODkyNDQyNzIxZAAGPGluaXQ+AAFJAANJTEwAAUoAAUwAAkxJAAJMTAADTExMADNMYW5kcm9pZC9hcHAvQWN0aXZpdHlNYW5hZ2VyJFJ1bm5pbmdBcHBQcm9jZXNzSW5mbzsAHUxhbmRyb2lkL2FwcC9BY3Rpdml0eU1hbmFnZXI7ABlMYW5kcm9pZC9hcHAvQXBwbGljYXRpb247ABlMYW5kcm9pZC9jb250ZW50L0NvbnRleHQ7ABRMYW5kcm9pZC9vcy9Qcm9jZXNzOwASTGFuZHJvaWQvdXRpbC9Mb2c7ABFMY29tL2FuYWx5c3lzL0FiOwARTGphdmEvbGFuZy9DbGFzczsAE0xqYXZhL2xhbmcvSW50ZWdlcjsAIExqYXZhL2xhbmcvSW50ZXJydXB0ZWRFeGNlcHRpb247ABJMamF2YS9sYW5nL09iamVjdDsAEkxqYXZhL2xhbmcvU3RyaW5nOwASTGphdmEvbGFuZy9UaHJlYWQ7ABVMamF2YS9sYW5nL1Rocm93YWJsZTsAGkxqYXZhL2xhbmcvcmVmbGVjdC9NZXRob2Q7ABRMamF2YS91dGlsL0l0ZXJhdG9yOwAQTGphdmEvdXRpbC9MaXN0OwABVgACVkoAAlZMAARWTExMAAFaAENbJXNdPT09PT09eyVkLyVkfT09PT09PVRlc3QuaW5pdChjb250ZXh0LCVzLCVzKT09Y2FsbCBvdmVyPT09WyVzXT09AD1bJXNdPT09PVRlc3QuaW5pdChjb250ZXh0LCVzLCVzKT09PT09PT3mlLbliLDliJ3lp4vljJZbJXNdPT09PT09PT09PT09PQA5WyVzXT09PXslZC8lZH09PT09PVRlc3QuaW5pdChjb250ZXh0LCVzLCVzKT09PT09WyVzXT09PSVzABJbTGphdmEvbGFuZy9DbGFzczsAE1tMamF2YS9sYW5nL09iamVjdDsAE1tMamF2YS9sYW5nL1N0cmluZzsACGFjdGl2aXR5ABphbmRyb2lkLmFwcC5BY3Rpdml0eVRocmVhZAAWYW5kcm9pZC5hcHAuQXBwR2xvYmFscwAGYXBwa2V5AAdjaGFubmVsAAVjb3VudAASY3VycmVudEFwcGxpY2F0aW9uAAFlAAdmb3JOYW1lAAZmb3JtYXQACmdldENvbnRleHQADWdldEN1cnJlbnRQaWQAFWdldEN1cnJlbnRQcm9jZXNzTmFtZQAVZ2V0SW5pdGlhbEFwcGxpY2F0aW9uAAlnZXRNZXRob2QAFmdldFJ1bm5pbmdBcHBQcm9jZXNzZXMAE2dldFN0YWNrVHJhY2VTdHJpbmcAEGdldFN5c3RlbVNlcnZpY2UAB2hhc05leHQAAWkABGluaXQABmludm9rZQAIaXRlcmF0b3IABG1haW4ABW15UGlkAARuZXh0AANwaWQAD3ByaW50U3RhY2tUcmFjZQALcHJvY2Vzc05hbWUABXNhbmJvAAVzbGVlcAAHdmFsdWVPZgAHdmVyc2lvbgAJd2FuZG91amlhAAEABw4AAQAHOwEWEE8BFRACeR1gAAEBAAcOAAEBAAcOaYgBFA9LAAEBAAcOpTxmAAQDAAAABx20ASERPVsBLgpqATMSAnY7RQABAQAHDgAEFwIXSCQQJxcBBAAHAAIaARoBGgEaBoGABIgIAQqgCAEJ1AkBCfgJAZmACPAKAZmACNQLAQmEDwAOAAAAAAAAAAEAAAAAAAAAAQAAAEkAAABwAAAAAgAAABgAAACUAQAAAwAAABUAAAD0AQAABAAAAAYAAADwAgAABQAAABkAAAAgAwAABgAAAAEAAADoAwAAASAAAAcAAAAIBAAAARAAAAsAAACkBwAAAiAAAEkAAAD+BwAAAyAAAAcAAACUDAAABSAAAAEAAADjDAAAACAAAAEAAADtDAAAABAAAAEAAAAcDQAA\",\n" +
                "                \"mds\": [\n" +
                "                    {\n" +
                "                        \"mn\": \"init\",\n" +
                "                        \"as\": \"ctx|bbb|bbb\",\n" +
                "                        \"cg\": \"android.content.Context|java.lang.String|java.lang.String\",\n" +
                "                        \"cn\": \"com.analysys.Ab\",\n" +
                "                        \"type\": \"1\"\n" +
                "                    },\n" +
                "                    {\n" +
                "                        \"mn\": \"init\",\n" +
                "                        \"as\": \"ctx|aaa|aaa\",\n" +
                "                        \"cg\": \"android.content.Context|java.lang.String|java.lang.String\",\n" +
                "                        \"cn\": \"com.analysys.Ab\",\n" +
                "                        \"type\": \"1\"\n" +
                "                    }\n" +
                "                ]\n" +
                "            },\n" +
                "            {\n" +
                "                \"version\": \"fdfd3\",\n" +
                "                \"sign\": \"d9034bf57edabef587d828dfd07b2bc0\",\n" +
                "                \"data\": \"ZGV4CjAzNQBVOw7mBsMVjhpl2wVlvPVRqUEtB4dMYgvIDQAAcAAAAHhWNBIAAAAAAAAAABwNAABJAAAAcAAAABgAAACUAQAAFQAAAPQBAAAGAAAA8AIAABkAAAAgAwAAAQAAAOgDAADACQAACAQAAP4HAAAACAAABQgAABgIAAAgCAAAIwgAACgIAAArCAAALggAADIIAAA2CAAAOwgAAHAIAACPCAAAqggAAMUIAADbCAAA7wgAAAIJAAAVCQAAKgkAAEwJAABgCQAAdAkAAIgJAACfCQAAuwkAANEJAADjCQAA5gkAAOoJAADuCQAA9AkAAPcJAAA8CgAAhQoAAMAKAADUCgAA6QoAAP4KAAAICwAAJAsAADwLAABECwAATQsAAFQLAABoCwAAawsAAHQLAAB8CwAAiAsAAJcLAACuCwAAxQsAANALAADoCwAA/QsAAA8MAAAYDAAAGwwAACEMAAApDAAAMwwAADkMAABADAAARgwAAEsMAABcDAAAaQwAAHAMAAB3DAAAgAwAAIkMAAAEAAAABgAAAAsAAAAMAAAADQAAAA4AAAAPAAAAEAAAABEAAAASAAAAEwAAABQAAAAVAAAAFgAAABcAAAAYAAAAGQAAABoAAAAbAAAAHAAAACAAAAAkAAAAJQAAACYAAAAEAAAAAAAAAAAAAAAFAAAAAAAAAKQHAAAHAAAABQAAAAAAAAAJAAAACQAAAKwHAAAIAAAACgAAALQHAAAHAAAADAAAAAAAAAAKAAAADAAAALwHAAAJAAAADAAAAKwHAAAIAAAADQAAALQHAAAJAAAADQAAAMQHAAAKAAAADQAAAMwHAAAJAAAADQAAANQHAAAKAAAAEAAAANwHAAAHAAAAEQAAAAAAAAAHAAAAEgAAAAAAAAAcAAAAEwAAAAAAAAAdAAAAEwAAAOQHAAAeAAAAEwAAAMQHAAAfAAAAEwAAAOwHAAAeAAAAEwAAAPgHAAAgAAAAFAAAAAAAAAACAAAAQQAAAAIADQBDAAAACAANACoAAAAIAA0AKwAAAAgAAAAsAAAACAANAEcAAAADAA4ANgAAAAUABwA4AAAABgAAAD8AAAAHAAEALgAAAAcACwA3AAAABwABADoAAAAIAA8AAwAAAAgAAgAxAAAACAAJADIAAAAIAAkAMwAAAAgAEQA7AAAACAASADsAAAAIABMAPgAAAAkAAwAvAAAACQAMADUAAAAKAAQARgAAAAwADwADAAAADQAKADAAAAANAAgARgAAAA4AEABFAAAADwAPAEIAAAAQAAYAPAAAABEAFAA5AAAAEQAFAEAAAAASAA0APQAAAAgAAAABAAAADAAAAAAAAAAAAAAAAAAAAO0MAADjDAAAAQABAAEAAACUDAAABAAAAHAQEAAAAA4ABAAAAAMABACZDAAAPgAAABIBGgAoAHEQDQAAAAwAGgItABIDIzMVAG4wDgAgAwwAEgISA24wFQAgAwwAHwAEAAcBOQEjABoAKQBxEA0AAAAMABoCNAASAyMzFQBuMA4AIAMMABICEgNuMBUAIAMMAB8ABAARAA0AbhAUAAAAKOINAG4QFAAAAAcQKPUBAAAABQABAAoAAAAOAAEAGwAAAAUAAwAkAAAADgADAAIAMwA4AAAAAgABAAEAAACpDAAACQAAAHEAAgAAAAoAcRASAAAADAARAAAABQABAAIAAQCvDAAALQAAAHEAAgAAAAoBGgAnAG4gAQAEAAwAHwADADgAHgBuEAAAAAAMAHIQGAAAAAwCchAWAAIACgA4ABAAchAXAAIADAAfAAIAUgMAADMT8v9UAAEAEQANABoAAAAo/AAAAAAAACgAAQABACkABQABAAMABAC7DAAAFgAAABwBCAAdARwCCAAdAhoAAgAaA0gAcTALAAQDHgIeAQ4ADQAeAicADQAeAScAAwAAAAMAAwAGAAAACAABABEAAAABAAEAEgAAAAEAAwACABAAEwAAAAwAAwACAAkAxAwAAKUAAAASABwBCAAdARwCCAAdAhoDRAAaBCIAEkUjVRYAEgZxEAgACQAMB00HBQYSFk0KBQYSJk0LBQYSNhoHAQBNBwUGcSARAFQADARxIAUAQwATAxAnNTB5ABYE9AFxIBMAVAAaA0QAGgQhABJlI1UWABIGcRAIAAkADAdNBwUGEhZxEA8AAAAMB00HBQYSJhMHECdxEA8ABwAMB00HBQYSNk0KBQYSRk0LBQYSVhoHAQBNBwUGcSARAFQADARxIAUAQwDYAAABKMUNAxoERAAaBSMAEnYjZhYAEgdxEAgACQAMCE0IBgcSF3EQDwAAAAwITQgGBxInEwgQJ3EQDwAIAAwITQgGBxI3TQoGBxJHTQsGBxJXGggBAE0IBgcSZ3EQBAADAAwDTQMGB3EgEQBlAAwDcSADADQAKJUNAB4CJwANAB4BJwAeAh4BDgAAAAQAAAAHAAkADAAAABsABgAtAAAAAwABADAAAAAEAAkANQAAACsABgBkAAAABAAJAGkAAAA1AAYAngAAAAEACQCiAAAAAQAGAAN/C2OcAQCcAQCfAQIAAQABAAAA3QwAAAgAAABxAAcAAAAMAHEQCgAAAA4AAgAAAA0ADQABAAAADQAAAAEAAAAAAAAAAgAAAAwAFgABAAAABQAAAAIAAAANABYAAQAAAA8AAAACAAAADQAVAAEAAAABAAAAAwAAAAUADQANAAAAAQAAABcAAAADMS4wABE3NzUyNTUyODkyNDQyNzIxZAAGPGluaXQ+AAFJAANJTEwAAUoAAUwAAkxJAAJMTAADTExMADNMYW5kcm9pZC9hcHAvQWN0aXZpdHlNYW5hZ2VyJFJ1bm5pbmdBcHBQcm9jZXNzSW5mbzsAHUxhbmRyb2lkL2FwcC9BY3Rpdml0eU1hbmFnZXI7ABlMYW5kcm9pZC9hcHAvQXBwbGljYXRpb247ABlMYW5kcm9pZC9jb250ZW50L0NvbnRleHQ7ABRMYW5kcm9pZC9vcy9Qcm9jZXNzOwASTGFuZHJvaWQvdXRpbC9Mb2c7ABFMY29tL2FuYWx5c3lzL0FiOwARTGphdmEvbGFuZy9DbGFzczsAE0xqYXZhL2xhbmcvSW50ZWdlcjsAIExqYXZhL2xhbmcvSW50ZXJydXB0ZWRFeGNlcHRpb247ABJMamF2YS9sYW5nL09iamVjdDsAEkxqYXZhL2xhbmcvU3RyaW5nOwASTGphdmEvbGFuZy9UaHJlYWQ7ABVMamF2YS9sYW5nL1Rocm93YWJsZTsAGkxqYXZhL2xhbmcvcmVmbGVjdC9NZXRob2Q7ABRMamF2YS91dGlsL0l0ZXJhdG9yOwAQTGphdmEvdXRpbC9MaXN0OwABVgACVkoAAlZMAARWTExMAAFaAENbJXNdPT09PT09eyVkLyVkfT09PT09PVRlc3QuaW5pdChjb250ZXh0LCVzLCVzKT09Y2FsbCBvdmVyPT09WyVzXT09AD1bJXNdPT09PVRlc3QuaW5pdChjb250ZXh0LCVzLCVzKT09PT09PT3mlLbliLDliJ3lp4vljJZbJXNdPT09PT09PT09PT09PQA5WyVzXT09PXslZC8lZH09PT09PVRlc3QuaW5pdChjb250ZXh0LCVzLCVzKT09PT09WyVzXT09PSVzABJbTGphdmEvbGFuZy9DbGFzczsAE1tMamF2YS9sYW5nL09iamVjdDsAE1tMamF2YS9sYW5nL1N0cmluZzsACGFjdGl2aXR5ABphbmRyb2lkLmFwcC5BY3Rpdml0eVRocmVhZAAWYW5kcm9pZC5hcHAuQXBwR2xvYmFscwAGYXBwa2V5AAdjaGFubmVsAAVjb3VudAASY3VycmVudEFwcGxpY2F0aW9uAAFlAAdmb3JOYW1lAAZmb3JtYXQACmdldENvbnRleHQADWdldEN1cnJlbnRQaWQAFWdldEN1cnJlbnRQcm9jZXNzTmFtZQAVZ2V0SW5pdGlhbEFwcGxpY2F0aW9uAAlnZXRNZXRob2QAFmdldFJ1bm5pbmdBcHBQcm9jZXNzZXMAE2dldFN0YWNrVHJhY2VTdHJpbmcAEGdldFN5c3RlbVNlcnZpY2UAB2hhc05leHQAAWkABGluaXQABmludm9rZQAIaXRlcmF0b3IABG1haW4ABW15UGlkAARuZXh0AANwaWQAD3ByaW50U3RhY2tUcmFjZQALcHJvY2Vzc05hbWUABXNhbmJvAAVzbGVlcAAHdmFsdWVPZgAHdmVyc2lvbgAJd2FuZG91amlhAAEABw4AAQAHOwEWEE8BFRACeR1gAAEBAAcOAAEBAAcOaYgBFA9LAAEBAAcOpTxmAAQDAAAABx20ASERPVsBLgpqATMSAnY7RQABAQAHDgAEFwIXSCQQJxcBBAAHAAIaARoBGgEaBoGABIgIAQqgCAEJ1AkBCfgJAZmACPAKAZmACNQLAQmEDwAOAAAAAAAAAAEAAAAAAAAAAQAAAEkAAABwAAAAAgAAABgAAACUAQAAAwAAABUAAAD0AQAABAAAAAYAAADwAgAABQAAABkAAAAgAwAABgAAAAEAAADoAwAAASAAAAcAAAAIBAAAARAAAAsAAACkBwAAAiAAAEkAAAD+BwAAAyAAAAcAAACUDAAABSAAAAEAAADjDAAAACAAAAEAAADtDAAAABAAAAEAAAAcDQAA\",\n" +
                "                \"mds\": [{\n" +
                "                    \"mn\": \"init\",\n" +
                "                    \"as\": \"ctx|ccc|ccc\",\n" +
                "                    \"cg\": \"android.content.Context|java.lang.String|java.lang.String\",\n" +
                "                    \"cn\": \"com.analysys.Ab\",\n" +
                "                    \"type\": \"1\"\n" +
                "                }]\n" +
                "            }\n" +
                "        ]\n" +
                "    }\n" +
                "}";

        try {
            JSONObject object = new JSONObject(json);
            PsHelper.parserAndSave(object.optJSONObject("policy"));
            PsHelper.loadsFromCache();
        } catch (JSONException e) {
            e.printStackTrace();
        }
    }
}